---
title: "datatidy"
author: "Ying-Jung Deweese"
date: "January 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, warning = FALSE,message = FALSE}
library(dplyr)
library(tidyr)

```

to call a function from a specific package 'package_name::function_name(...)'


#Data Cleaning

Read in data file

```{r}
catch_df<- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1", method = "libcurl"),
                    stringsAsFactors = FALSE)
head(catch_df)
```

ctrl+shift+M %>% pipe opearator

*Remove marginal sum and note column
*Move from wide to long format
```{r}
catch_long<-catch_df %>% 
  #negative value remove columns
  select(-All,-notesRegCode) %>% 
  gather(key="species",value = "catch",-Year,-Region)

head(catch_long)


```






```{r}
catch_clean<-catch_long %>% 
  rename(catch_thousands=catch) #%>% 
  #mutate(catch = catch_thousands*1000)
head(catch_clean)

```

```{r}


test_catch<-as.integer(catch_clean$catch_thousands)

i<-which(is.na(test_catch) == T)

catch_clean[i,]

```


#Split-Apply-Combine





#Joins